import { ExternalLink, Globe, History, Link2, QrCode, Save } from "lucide-react";
import { formatDateTime } from "../../utils/adminDashboardUtils";
import { EmptyState } from "./AdminDashboardShared";

// Ham nay dung de render tab admin quan ly URL website chinh va QR tuong ung.
// Nhan vao: currentConfig, history, websiteUrl draft, handlers va loading state.
// Tra ve: JSX cho form nhap URL, preview QR hien tai va bang lich su phien ban.
export default function AdminWebsiteQrPanel({
  currentConfig,
  history,
  websiteUrl,
  onWebsiteUrlChange,
  onSave,
  isLoading,
  isSaving,
}) {
  const handleSubmit = (event) => {
    event.preventDefault();
    onSave();
  };

  return (
    <section className="admin-panel-card">
      <div className="admin-panel-heading">
        <div>
          <span className="admin-kicker">Website QR Control</span>
          <h3>Main website URL and QR output</h3>
        </div>
        <div className="admin-heading-badge">
          <Link2 size={16} />
          {currentConfig ? `Version ${currentConfig.changeNumber}` : "Not configured yet"}
        </div>
      </div>

      <div className="admin-website-layout">
        <form className="admin-website-form-card" onSubmit={handleSubmit}>
          <div className="admin-field-block">
            <label className="admin-field-label" htmlFor="website-qr-url">
              Main Website URL
            </label>
            <input
              id="website-qr-url"
              className="admin-text-input"
              type="url"
              value={websiteUrl}
              onChange={(event) => onWebsiteUrlChange(event.target.value)}
              placeholder="https://your-domain.com"
              autoComplete="url"
            />
            <p className="admin-muted-copy">
              Save a new URL here and the backend will generate a fresh QR image, store it in
              `backend/app/QRURL`, and keep the history in the database.
            </p>
          </div>

          <div className="admin-field-block">
            <span className="admin-field-label">Filename Rule</span>
            <div className="admin-readonly-card">url_&lt;change_number&gt;_&lt;compact_website&gt;.png</div>
            <p className="admin-muted-copy">
              The compact website part is generated by removing symbols and spaces from the current URL.
            </p>
          </div>

          <div className="admin-form-actions">
            <button type="submit" className="admin-action-btn success" disabled={isSaving}>
              <Save size={16} />
              {isSaving ? "Saving..." : "Save Website QR"}
            </button>
            {currentConfig ? (
              <a className="admin-action-btn ghost" href={currentConfig.websiteUrl} target="_blank" rel="noreferrer">
                <ExternalLink size={16} />
                Open Current Website
              </a>
            ) : null}
          </div>
        </form>

        <div className="admin-website-preview-card">
          {isLoading && !currentConfig ? (
            <EmptyState icon={QrCode} title="Loading website QR" description="The current website QR configuration is being loaded." />
          ) : currentConfig ? (
            <>
              <div className="admin-qr-preview-shell">
                <img src={currentConfig.qrImageUrl} alt={`QR for ${currentConfig.websiteUrl}`} className="admin-qr-preview-image" />
              </div>

              <div className="admin-qr-meta-grid">
                <div className="admin-qr-meta-card">
                  <span>Current version</span>
                  <strong>#{currentConfig.changeNumber}</strong>
                </div>
                <div className="admin-qr-meta-card">
                  <span>File name</span>
                  <strong>{currentConfig.fileName}</strong>
                </div>
                <div className="admin-qr-meta-card wide">
                  <span>Website URL</span>
                  <strong>{currentConfig.websiteUrl}</strong>
                </div>
                <div className="admin-qr-meta-card wide">
                  <span>Generated at</span>
                  <strong>{formatDateTime(currentConfig.createdAt)}</strong>
                </div>
              </div>

              <div className="admin-inline-actions">
                <a className="admin-action-btn ghost" href={currentConfig.qrImageUrl} target="_blank" rel="noreferrer">
                  <QrCode size={16} />
                  View QR File
                </a>
                <a className="admin-action-btn ghost" href={currentConfig.websiteUrl} target="_blank" rel="noreferrer">
                  <Globe size={16} />
                  Open Website
                </a>
              </div>
            </>
          ) : (
            <EmptyState icon={Link2} title="No website QR yet" description="Enter the main website URL, save it, and the first QR version will appear here." />
          )}
        </div>
      </div>

      <div className="admin-history-block">
        <div className="admin-section-caption">
          <History size={18} />
          <span>Website QR version history</span>
        </div>

        {history.length > 0 ? (
          <div className="admin-table-shell">
            <table className="admin-table admin-history-table">
              <thead>
                <tr>
                  <th>Version</th>
                  <th>Website URL</th>
                  <th>File name</th>
                  <th>Generated at</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {history.map((historyRow) => (
                  <tr key={historyRow.configId}>
                    <td>
                      <div className="admin-cell-title">#{historyRow.changeNumber}</div>
                      <div className="admin-cell-subtitle">{historyRow.compactUrl}</div>
                    </td>
                    <td>
                      <div className="admin-cell-title">{historyRow.websiteUrl}</div>
                    </td>
                    <td>
                      <div className="admin-cell-title">{historyRow.fileName}</div>
                    </td>
                    <td>
                      <div className="admin-cell-title">{formatDateTime(historyRow.createdAt)}</div>
                    </td>
                    <td>
                      <div className="admin-action-row">
                        <a className="admin-action-btn ghost" href={historyRow.qrImageUrl} target="_blank" rel="noreferrer">
                          <QrCode size={16} />
                          View QR
                        </a>
                        <a className="admin-action-btn ghost" href={historyRow.websiteUrl} target="_blank" rel="noreferrer">
                          <ExternalLink size={16} />
                          Open URL
                        </a>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        ) : (
          <EmptyState icon={History} title="No history available" description="The first saved website URL will start the QR version history for the admin team." />
        )}
      </div>
    </section>
  );
}
